// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElectronVersions: typeof import('./components/ElectronVersions.vue')['default']
    ReactiveCounter: typeof import('./components/ReactiveCounter.vue')['default']
    ReactiveHash: typeof import('./components/ReactiveHash.vue')['default']
  }
}

export { }
