// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElectronVersions: typeof import('./components/ElectronVersions.vue')['default']
    ReactiveCounter: typeof import('./components/ReactiveCounter.vue')['default']
    ReactiveHash: typeof import('./components/ReactiveHash.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
